# Generated by Django 4.2 on 2023-05-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-cart']},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
