# Generated by Django 4.2 on 2023-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_cartitem_options_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-quantity']},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
