# Generated by Django 4.2 on 2023-06-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_shipping_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='type',
            new_name='name',
        ),
    ]
