# Generated by Django 4.2 on 2023-06-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_type_shipping_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=10)),
                ('discount_multiplier', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
