# Generated by Django 4.2 on 2023-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount_code',
            field=models.CharField(max_length=50),
        ),
    ]
