# Generated by Django 4.2 on 2023-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_promo_discount_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='payment_logo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='Shipping',
            new_name='ShippingMethod',
        ),
    ]
