# Generated by Django 4.2 on 2023-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_paymentmethod_rename_shipping_shippingmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='PLN', max_length=10),
            preserve_default=False,
        ),
    ]
