# Generated by Django 4.2 on 2023-06-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
