# Generated by Django 4.2 on 2023-06-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_payment_order_uuid_payment_payment_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_uuid',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='payment',
            name='hosted_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
