# Generated by Django 4.2 on 2023-07-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='discount_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='promo',
            old_name='discount_multiplier',
            new_name='multiplier',
        ),
        migrations.AddField(
            model_name='promo',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
