# Generated by Django 4.2 on 2023-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_rename_discount_code_promo_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
