# Generated by Django 4.2 on 2023-07-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.order')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.promo')),
            ],
        ),
    ]
