# Generated by Django 4.2 on 2023-07-29 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_promoactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoactivation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promoactivation',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.promo'),
        ),
    ]
