# Generated by Django 4.2 on 2023-08-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_promoactivation_user_alter_promoactivation_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoactivation',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
