# Generated by Django 4.2 on 2023-08-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_userprofile_name_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='uuid',
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.CharField(default='\x01\x02\x03\x04\x05\x06\x07\x08\t\n', max_length=200),
            preserve_default=False,
        ),
    ]
